# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Graham Clifford
email: gclifford@u.northwestern.edu
description: >- # this means to ignore newlines until "baseurl:"
  Master of Science in Robotics student at Northwestern University
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: n/a
github_username:  gjcliff

# Build settings
#theme: jekyll-theme-midnight
remote_theme: vszhub/not-pure-poole
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

cover_image: /shirley_daytime.JPG
avatar: /me_square.png
paginate: 10
permalink: "/:title/"

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Graham Clifford
  url: https://github.com/gjcliff/
  email: gclifford@u.northwestern.edu

collections:
  projects:
    output: true
    permalink: /projects/:path/

google_analytics: G-RT7CVF8GLG

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-RT7CVF8GLG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RT7CVF8GLG');
</script>
